package com.testeando.botonreconoceraudio;

/*
TODO List:
- Mejorar la interfaz de usuario, HAY PARTES QUE SE VEN MUY PEQUEÑAS, PENSAR QUE HACER CON ESO, REALMENTE ESO LO QUE HAREMOS SERÁ MANDARLO A LA WEB

- PENSAR QUE HACEMOS CUANDO EL % DE EMOCION NO ESTÁ CLARO, A LO MEJOR TENEMOS QUE CAMBIAR
LA API PARA QUE NO SOLO NOS DEVUELVA EL VALOR MAS GRANDE, SI NO QUE CUANDO ESE VALOR NO SEA TAN
GRANDE NOS DE MAS COSAS O ALGO ASI

- Pagina web (?)

*/
public class TODOList {
}
